export const DEFAULT_PROVIDER_MAX_CONCURRENCY = 1;

export const DEFAULT_PROVIDER_QUEUE_TIMEOUT_MS = 30_000;

export const GLOBAL_MAX_CONCURRENT_SPAWNS = 5;

export const MAX_ERROR_STDERR_BYTES = 4096;
