export const SKILL_CONTENT_INTRO_LINES = [
  '---',
  'name: using-agentic-mcp',
  'description: Use when an AI agent needs a repeatable workflow to get a real answer or compare providers through agentic-mcp, with discovery, proof, and CLI fallback steps.',
  '---',
  '',
  '# Using agentic-mcp',
  '',
  '## Overview',
  '',
  'Use this skill when the goal is a working outcome: get a real answer from the provider already installed on the machine, compare multiple providers on one prompt, or configure one MCP client entry instead of wiring providers separately. Start by discovering providers, prove one provider works with `ask_<provider>`, then use `ask_all` only for deliberate comparison.',
  '',
  '## When to Use',
  '',
  '- Getting to a first successful provider answer through `agentic-mcp`',
  '- Comparing multiple providers on the same prompt without bespoke glue',
  '- Using one repeatable workflow for MCP tools and CLI fallback',
  '- Resuming or inspecting multi-turn provider sessions',
  '- Reviewing usage, latency, and success metrics',
  '',
  'Do NOT use for: general skill authoring (`skills-writing`), non-agentic-mcp MCP servers.',
  '',
  'Do NOT use for: general skill authoring (`skills-writing`), non-agentic-mcp MCP servers.',
  '',
  '## Command Selection',
  '',
  '| Need | MCP tool | CLI command | When to use |',
  '| --- | --- | --- | --- |',
  '| Need to discover detected providers | `list_providers` | `agentic-mcp list_providers` | Before any provider-specific work |',
  '| Need limited proof for one provider | `ping_<provider>` | `agentic-mcp ping_<provider>` | Before the first real ask, not as final proof |',
  '| Need to inspect provider-specific capabilities | `help_<provider>` | `agentic-mcp help_<provider>` | Only when you need flags, models, or behavior details |',
  '| Need one provider to answer a task | `ask_<provider>` | `agentic-mcp ask_<provider> "..."` | Default path for normal work and the first real proof |',
  '| Need to compare providers on the same prompt | `ask_all` | `agentic-mcp ask_all "..." --providers claude,gemini` | Only when comparison itself is the goal |',
  '| Need to resume or inspect multi-turn work | `sessions_<provider>` then `ask_<provider>` with `session_id` | `agentic-mcp sessions_<provider>` then `agentic-mcp ask_<provider> "..." --session-id <id>` | Continue existing context instead of starting over |',
  '| Need usage and reliability metrics | `provider_metrics` | `agentic-mcp provider_metrics` | After runs, debugging, or performance review |',
  '| Need to install or update the integration | setup CLI | `agentic-mcp init` or `agentic-mcp setup --client claude-code --yes` | New machine, fresh repo, or before choosing a client config |',
  '',
  'Providers: `claude`, `copilot`, `codex`, `gemini`, `opencode`',
  '',
  '## Discovery-First Workflow',
  '',
  '1. **Load tools**: `ToolSearch("select:mcp__agentic-mcp__list_providers")` if the MCP tool surface is deferred.',
  '2. **Discover**: `list_providers` to see which providers are detected.',
  '3. **Check limited proof**: `ping_<provider>` for the provider you intend to use first.',
  '4. **Understand**: `help_<provider>` only when you need supported models, flags, or behavior details.',
  '5. **Prove real usage**: `ask_<provider>` for focused work, `ask_all` only for side-by-side comparison.',
  '6. **Continue**: `sessions_<provider>` and `--session-id <id>` when you need multi-turn continuity.',
  '7. **Review**: `provider_metrics` when you need latency, success, or usage data.',
  '',
  '## Setup (New Environment)',
  '',
  '```bash',
  'npx agentic-mcp init',
  'npx agentic-mcp setup --minimal',
  'npx agentic-mcp setup --client claude-code --yes',
  '```',
  '',
  'Use `init` to install the skill first, then run the full client-specific setup command when you are ready to write MCP config.',
  '',
  'Then verify in order: `list_providers` -> `ping_claude` -> `ask_claude "Reply with OK and your provider name."`',
] as const;
