export const SKILL_CONTENT_INTRO_LINES = [
  '---',
  'name: using-agentic-mcp',
  'description: Use when a user needs to ask another model a question or make it perform a task, discovering providers, checking readiness, querying one provider with ask_<provider>, comparing providers with ask_all, resuming sessions_<provider>, reviewing provider_metrics, or falling back to CLI commands.',
  '---',
  '',
  '# Using agentic-mcp',
  '',
  '## Overview',
  '',
  'agentic-mcp exposes the same workflow through MCP tools and direct CLI commands. Prefer MCP tools when tool calling is available. Use CLI fallback when MCP tools are unavailable. The safe order is always: discover providers, verify readiness, inspect capabilities, then ask.',
  '',
  '## When to Use',
  '',
  '- Setting up agentic-mcp in a new environment',
  '- Discovering which providers are configured',
  '- Verifying a provider is ready before sending work',
  '- Checking provider-specific capabilities before choosing a model or workflow',
  '- Sending one task to one provider',
  '- Sending the same task to multiple providers for comparison',
  '- Resuming or inspecting multi-turn provider sessions',
  '- Reviewing usage, latency, and success metrics',
  '- Falling back to CLI commands when MCP tool calling is unavailable',
  '',
  'Do NOT use for: general skill authoring (`skills-writing`), non-agentic-mcp MCP servers.',
  '',
  '## Command Selection',
  '',
  '| Need | MCP tool | CLI command | When to use |',
  '| --- | --- | --- | --- |',
  '| Need to discover available providers | `list_providers` | `agentic-mcp list_providers` | Before any provider-specific work |',
  '| Need to confirm one provider is ready | `ping_<provider>` | `agentic-mcp ping_<provider>` | Before claiming a provider is available |',
  '| Need to inspect provider-specific capabilities | `help_<provider>` | `agentic-mcp help_<provider>` | Before assuming flags, models, or behavior |',
  '| Need one provider to answer a task | `ask_<provider>` | `agentic-mcp ask_<provider> "..."` | Default path for normal work |',
  '| Need to compare providers on the same prompt | `ask_all` | `agentic-mcp ask_all "..." --providers claude,gemini` | Only when comparison itself is the goal |',
  '| Need to resume or inspect multi-turn work | `sessions_<provider>` then `ask_<provider>` with `session_id` | `agentic-mcp sessions_<provider>` then `agentic-mcp ask_<provider> "..." --session-id <id>` | Continue existing context instead of starting over |',
  '| Need usage and reliability metrics | `provider_metrics` | `agentic-mcp provider_metrics` | After runs, debugging, or performance review |',
  '| Need to install or update the integration | setup CLI | `agentic-mcp init` or `agentic-mcp setup --minimal` | New machine, fresh repo, or before choosing a client config |',
  '',
  'Providers: `claude`, `copilot`, `codex`, `gemini`, `opencode`',
  '',
  '## Discovery-First Workflow',
  '',
  '1. **Load tools**: `ToolSearch("select:mcp__agentic-mcp__list_providers")` if the MCP tool surface is deferred.',
  '2. **Discover**: `list_providers` to see which providers are configured.',
  '3. **Verify**: `ping_<provider>` for the specific provider you intend to use.',
  '4. **Understand**: `help_<provider>` before assuming supported models, flags, or behavior.',
  '5. **Execute**: `ask_<provider>` for focused work, `ask_all` only for side-by-side comparison.',
  '6. **Continue**: `sessions_<provider>` and `--session-id <id>` when you need multi-turn continuity.',
  '7. **Review**: `provider_metrics` when you need latency, success, or usage data.',
  '',
  '## Setup (New Environment)',
  '',
  '```bash',
  'npx agentic-mcp init',
  'npx agentic-mcp setup --minimal',
  'npx agentic-mcp setup --client claude-code --yes',
  '```',
  '',
  'Use `init` or `setup --minimal` to install the skill first, then run the full client-specific setup command when you are ready to write MCP config.',
  '',
  'Then verify in order: `list_providers` -> `ping_claude` -> `help_claude`',
] as const;
