export const SKILL_CONTENT_GUIDE_LINES = [
  '',
  '## ask_<provider> Command Guide',
  '',
  'Use `ask_<provider>` when one provider should do the work.',
  '',
  'Important flags and when to use them:',
  '',
  '- `--model <name>` when the user asks for a specific model',
  '- `--file <path>` when the prompt refers to repository files or artifacts',
  '- `--context <text>` when extra steering or constraints are needed',
  '- `--stream-live` when the user wants live progress output',
  '- `--session-id <id>` when continuing an existing multi-turn session',
  '- `--async` when the request may take a while and should return immediately',
  '- `--job-id <id>` when checking the status or result of a prior async job',
  '',
  'Examples:',
  '',
  '```bash',
  'npx agentic-mcp ask_claude "Review this implementation" --file src/cli/domain-logic/cli.router.ts',
  'npx agentic-mcp ask_claude "Summarize the risks" --context "Focus on edge cases"',
  'npx agentic-mcp ask_claude "Show progress while reasoning" --stream-live',
  'npx agentic-mcp ask_claude "Continue the earlier investigation" --session-id session-123',
  'npx agentic-mcp ask_claude "Fix this bug" --async',
  'npx agentic-mcp ask_claude --job-id job-123',
  '```',
  '',
  '## ask_all Command Guide',
  '',
  'Use `ask_all` only when the same prompt should be sent to multiple providers for comparison.',
  '',
  'Important flags and when to use them:',
  '',
  '- `--provider <list>` is an alias for `--providers`; use either form to choose providers',
  '- `--providers <list>` limits the comparison set; values may be comma-separated or space-separated',
  '- `--model <name>` passes one shared model hint to every selected provider',
  '- `--models <name>` is an alias for `--model`',
  '- Use `--providers` for provider selection and `--model` for the shared model hint',
  '- If `--providers` and `--model` are combined, `--providers` chooses the providers and `--model` applies the shared model hint to those providers',
  '- When a selected provider rejects the shared model as unavailable or unsupported, `ask_all` returns that provider error directly instead of falling back to a different model',
  '- `--context <text>` adds shared guidance to the comparison prompt',
  '',
  'Examples:',
  '',
  '```bash',
  'npx agentic-mcp ask_all "Explain this architecture" --providers claude,gemini',
  'npx agentic-mcp ask_all "Compare bugfix approaches" --providers claude codex --context "Optimize for smallest safe diff"',
  'npx agentic-mcp ask_all "Compare providers" --providers gemini codex',
  'npx agentic-mcp ask_all "Use one shared model" --providers claude,gemini --model claude-sonnet-4',
  '```',
  '',
  '## Sessions and Metrics',
  '',
  '- `sessions_<provider>` lists known sessions for a provider.',
  '- `provider_metrics` shows which providers you actually used, how often they succeeded, and how long they took.',
  '- Use sessions before starting a new thread if continuity matters.',
  '- Use metrics after a batch of runs, during debugging, or when comparing provider behavior.',
  '',
  'Examples:',
  '',
  '```bash',
  'npx agentic-mcp sessions_claude',
  'npx agentic-mcp provider_metrics',
  '```',
  '',
  '## CLI Fallback',
  '',
  'When MCP tools are unavailable, use the CLI directly:',
  '',
  '```bash',
  'npx agentic-mcp list_providers',
  'npx agentic-mcp ping_claude',
  'npx agentic-mcp help_claude',
  'npx agentic-mcp ask_claude "Review this file" --file src/setup/common/skill-content.ts',
  'npx agentic-mcp ask_claude "Summarize the risks" --context "Focus on edge cases"',
  'npx agentic-mcp ask_claude "Show progress while reasoning" --stream-live',
  'npx agentic-mcp ask_claude "Fix this bug" --async',
  'npx agentic-mcp ask_claude --job-id job-123',
  'npx agentic-mcp sessions_claude',
  'npx agentic-mcp ask_all "Compare TypeScript validation libraries" --providers claude,gemini',
  'npx agentic-mcp provider_metrics',
  '```',
  '',
  '## Common Mistakes',
  '',
  '| Mistake | Fix |',
  '| --- | --- |',
  '| Calling `ask_<provider>` before `list_providers` | Discover detected providers first |',
  '| Treating `ping_<provider>` as final proof | Use it only for limited proof before a real ask |',
  '| Skipping `help_<provider>` and guessing provider capabilities | Read provider help only when you need flags or model details |',
  '| Using `ask_all` for single-provider work | Use `ask_<provider>` unless comparison is the actual goal |',
  '| Passing `--providers` to `ask_<provider>` or `--async` to `ask_all` | Match flags to the command family that supports them |',
  '| Starting a new thread when an existing session should continue | Check `sessions_<provider>` and reuse `--session-id <id>` |',
  '| Ignoring `provider_metrics` after repeated failures or slow runs | Use metrics to inspect success rate and latency |',
  '| Calling MCP tools without loading deferred tool surfaces first | Run `ToolSearch(...)` before invoking deferred tools |',
] as const;
