export {
  TOOL_REGISTRY_PROVIDER_CONFIG_STUB,
  TOOL_REGISTRY_PROVIDER_METRICS_TOOL_DEFINITION_STUB,
  TOOL_REGISTRY_RESOLVED_PROVIDER_ENTRY_STUB,
  TOOL_REGISTRY_RESOLVED_PROVIDER_STUB,
  TOOL_REGISTRY_SUCCESS_CALL_TOOL_RESULT_STUB,
} from './tool-registry.stub';
