export const HELP_TEXT = [
  'Usage: agentic-mcp [command] [options]',
  '',
  'Commands:',
  '  ask_<provider> <prompt>   Query a provider (e.g. ask_claude "explain X")',
  '  ask_all <prompt>          Query all providers in parallel',
  '  ping_<provider>           Check if a provider is available',
  '  help_<provider>           Show provider CLI help output',
  '  sessions_<provider>       List known ask sessions for a provider',
  '  list_providers            List all configured providers',
  '  provider_metrics          Show overall call statistics',
  '  setup                     Configure MCP client integration',
  '  init                      Install the skill and suggest MCP setup',
  '',
  'Options:',
  '  --config <path>           Path to providers config file',
  '  --model <name>            Model to use (ask commands)',
  '  --working-dir <path>      Working directory for the provider',
  '  --system-prompt <text>    System prompt',
  '  --auto-mode <value>       Auto-mode flag value',
  '  --effort <value>          Effort level',
  '  --max-budget <value>      Max budget',
  '  --context <text>          Additional prompt context',
  '  --file <path>             File to include (repeatable)',
  '  --stream-live             Stream live progress for ask_<provider> commands',
  '  --providers <list>        Comma-separated provider list (ask_all)',
  '  --async                   Run asynchronously',
  '  --job-id <id>             Job ID for async status checks',
  '  --session-id <id>         Session ID for multi-turn',
  '  --version                 Print version and exit',
  '  --help                    Print this help message and exit',
  '  --minimal                 Install the skill and print suggested MCP setup',
  '',
  'Examples:',
  '  agentic-mcp ask_claude "what is TypeScript?"',
  '  agentic-mcp ask_claude "show progress" --stream-live',
  '  agentic-mcp ask_claude "summarize this" --context "Focus on risks"',
  '  agentic-mcp ask_claude "fix this bug" --async',
  '  agentic-mcp ask_claude --job-id job-123',
  '  agentic-mcp sessions_claude',
  '  agentic-mcp ask_all "explain MCP" --providers claude,gemini',
  '  agentic-mcp list_providers',
  '  agentic-mcp ping_claude',
  '',
  'CLI subcommands call the matching MCP tools in-process.',
  '',
  'When run without a command, starts as an MCP stdio server.',
  '',
].join('\n');
