export const HELP_TEXT = [
  'Usage: agentic-mcp [command] [options]',
  '',
  'Commands:',
  '  ask_<provider> <prompt>   Query a provider (e.g. ask_claude "explain X")',
  '  review_<provider>         Review changes with a provider (e.g. review_codex --scope uncommitted)',
  '  ask_all <prompt>          Query all providers in parallel',
  '  ping_<provider>           Check limited provider proof',
  '  help_<provider>           Show provider CLI help output',
  '  sessions_<provider>       List known ask sessions for a provider',
  '  list_providers            List configured providers with detected status',
  '  provider_metrics          Show which providers you actually used',
  '  setup                     Configure MCP client integration',
  '  init                      Install the skill and suggest MCP setup',
  '',
  'Options:',
  '  --config <path>           Path to providers config file',
  '  --model <name>            Shared model hint; ask_all also accepts --models as an alias',
  '  --working-dir <path>      Working directory for the provider',
  '  --system-prompt <text>    System prompt',
  '  --auto-mode <value>       Auto-mode flag value',
  '  --effort <value>          Effort level',
  '  --max-budget <value>      Max budget',
  '  --context <text>          Additional prompt context',
  '  --file <path>             File to include (repeatable)',
  '  --scope <name>            Review scope: uncommitted, commit, or range',
  '  --commit <sha>            Commit SHA for review_<provider> when --scope commit',
  '  --base <ref>              Base ref for review_<provider> when --scope range',
  '  --stream-live             Stream live progress for ask_<provider> and review_<provider> commands',
  '  --providers <list>        ask_all provider selection; --provider alias and space-separated values are supported',
  '  --async                   Run asynchronously',
  '  --job-id <id>             Job ID for async status checks',
  '  --session-id <id>         Session ID for multi-turn',
  '  --version                 Print version and exit',
  '  --help                    Print this help message and exit',
  '  --minimal                 Install the skill and print suggested MCP setup',
  '',
  'ask_all combinations:',
  '  --provider/--providers choose providers',
  '  --model/--models choose one shared model hint for the selected providers',
  '  use --providers for provider selection and --model for the shared model',
  '  --providers claude,gemini --model claude-sonnet-4 applies the shared model to those providers',
  '',
  'Examples:',
  '  agentic-mcp ask_claude "what is TypeScript?"',
  '  agentic-mcp review_codex --scope uncommitted --working-dir .',
  '  agentic-mcp ask_claude "show progress" --stream-live',
  '  agentic-mcp ask_claude "summarize this" --context "Focus on risks"',
  '  agentic-mcp ask_claude "fix this bug" --async',
  '  agentic-mcp ask_claude --job-id job-123',
  '  agentic-mcp sessions_claude',
  '  agentic-mcp ask_all "explain MCP" --providers claude,gemini',
  '  agentic-mcp ask_all "compare providers" --providers gemini codex',
  '  agentic-mcp ask_all "use one shared model" --providers claude,gemini --model claude-sonnet-4',
  '  agentic-mcp list_providers',
  '  agentic-mcp ping_claude',
  '',
  'CLI subcommands call the matching MCP tools in-process.',
  '',
  'When run without a command, starts as an MCP stdio server.',
  '',
].join('\n');
