export const HELP_TEXT = [
  'Usage: agentic-mcp [command] [options]',
  '',
  'Commands:',
  '  ask_<provider> <prompt>   Query a provider (e.g. ask_claude "explain X")',
  '  ask_all <prompt>          Query all providers in parallel',
  '  ping_<provider>           Check if a provider is available',
  '  help_<provider>           Show provider CLI help output',
  '  list_providers            List all configured providers',
  '  provider_metrics          Show call statistics',
  '  setup                     Configure MCP client integration',
  '',
  'Options:',
  '  --config <path>           Path to providers config file',
  '  --model <name>            Model to use (ask commands)',
  '  --working-dir <path>      Working directory for the provider',
  '  --system-prompt <text>    System prompt',
  '  --auto-mode <value>       Auto-mode flag value',
  '  --effort <value>          Effort level',
  '  --max-budget <value>      Max budget',
  '  --file <path>             File to include (repeatable)',
  '  --providers <list>        Comma-separated provider list (ask_all)',
  '  --async                   Run asynchronously',
  '  --session-id <id>         Session ID for multi-turn',
  '  --version                 Print version and exit',
  '  --help                    Print this help message and exit',
  '',
  'Examples:',
  '  agentic-mcp ask_claude "what is TypeScript?"',
  '  agentic-mcp ask_codex "fix this bug" --model o4-mini',
  '  agentic-mcp ask_all "explain MCP" --providers claude,gemini',
  '  agentic-mcp list_providers',
  '  agentic-mcp ping_claude',
  '',
  'When run without a command, starts as an MCP stdio server.',
  '',
].join('\n');
